# SPDX-License-Identifier: MPL-2.0

version: 2

# Note: PDF/epub/htmlzip output is not supported when using MkDocs
formats:
  - htmlzip
  - pdf
  - epub

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

python:
 install:
 - requirements: docs/requirements.txt

# see: https://docs.readthedocs.io/en/stable/config-file/v2.html#supported-settings
