name: Continuous Integration
on: [push, pull_request]
jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        exclude: './thirdParty'
        clangFormatVersion: 11
